# Generated by Django 5.2.6 on 2025-10-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetId', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Account.account')),
            ],
        ),
    ]
