# Generated by Django 5.2.6 on 2025-09-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('notes', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('T', 'Transfer'), ('E', 'Expense'), ('I', 'Income'), ('S', 'Saving')], default='E', max_length=1)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transaction.transaction')),
                ('source', models.CharField(max_length=120)),
            ],
            bases=('Transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Transaction.transaction')),
                ('goalId', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('Transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transaction.transaction')),
                ('name', models.CharField(max_length=120)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Transaction.category')),
            ],
            bases=('Transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transaction.transaction')),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Account.account')),
            ],
            bases=('Transaction.transaction',),
        ),
    ]
