# Generated by Django 5.2.6 on 2025-09-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoalSetter', '0001_initial'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='goalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoalSetter.goal'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='transaction_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transaction.transaction'),
        ),
    ]
