# Generated by Django 5.2.6 on 2025-09-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('birthDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('balance', models.FloatField(default=0)),
                ('createdAt', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Account.user')),
            ],
        ),
    ]
