# Generated by Django 5.2.6 on 2025-09-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Transaction', '0002_alter_saving_goalid_alter_saving_transaction_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingSuggestion',
            fields=[
                ('suggestionId', models.AutoField(primary_key=True, serialize=False)),
                ('potentialSaving', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommendationText', models.CharField(max_length=120)),
                ('expenseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.expense')),
            ],
        ),
    ]
