# Generated by Django 5.2.6 on 2025-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_user_managers_rename_username_account_name_and_more'),
        ('GoalSetter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='accountGoal',
            field=models.ManyToManyField(through='GoalSetter.AccountGoal', to='Account.account'),
        ),
    ]
